config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, except: [:destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user

  validates :text, :user, presence: true
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord

  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password

  def encrypt_password
    if self.password.present?

      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

  if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
    user
  else
    nil
  end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def create_session(email, password)
    @user = User.authenticate(email, password)
    session[:user_id] = @user.id
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :load_question, only: [:show, :edit, :update, :destroy]

  before_action :authorize_user, except: [:create]

    # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'вы успешно залогинились'
    else
      flash.now.alert = 'Неверный адрес почты или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы разлогинились!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:index, :new, :create]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: 'вы уже залогинились' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'вы уже залогинились' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      create_session(@user.email, @user.password)
      redirect_to root_url, notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :username, :avatar_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Good Questionz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>

    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
        </div>

        <div class="header-nav">
          <% if current_user %>
              <%= link_to "@#{current_user.username}", user_path(current_user) %>
              <%= link_to 'Выйти', log_out_path %>
          <% else %>
              <%= link_to 'Зарегистрироваться', sign_up_path, class: 'button button-light button-small'	%>
              <%= link_to 'Войти', log_in_path, class: 'button button-light button-small'	%>
          <% end %>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="container">

        <% if flash.any? %>
            <div class="content-wrapper buffer-both">
              <% flash.each do |name, message| %>
                <%= content_tag :div, message, class: "flash-#{name}" %>
              <% end %>
            </div>
        <% end %>

      <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
      <% if @question.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                  <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label :text, 'Вопрос', class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%# Простая авторизация - может ли текущий юзер править вопрос? %>
      <% if current_user.present? && current_user == @question.user %>
          <div class="form-field">
            <%= f.label :answer, 'Ответ', class: 'form-label' %>
            <%= f.text_area :answer, class: 'form-textarea' %>
          </div>
      <% end %>

      <div class="form-action buffer-both">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        или
        <%= link_to 'Вернуться', user_path(@question.user) %>
      </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
  <div class="questions-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: "Точно удалить вопрос?"} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
        <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
        <%# в поле errors модели (в нашем случае @users). %>
        <% if @user.errors.any? %>
            <div class="form-errors">
              <ul>
                <% for message in @user.errors.full_messages %>
                    <li class="form-error-message"><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%# С помощью методов label и text_field у объекта f мы создаем теги %>
        <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
        <div class="form-field">
          <%= f.label :username, class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <%# Поступаем аналогично для других полей %>
        <div class="form-field">
          <%= f.label 'Ваше имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label 'URL вашей аватарки', class: 'form-label' %>
          <%= f.text_field :avatar_url, class: 'form-text-field' %>
        </div>

        <div class="buffer-top-large buffer-bottom">
          Если не хотите менять пароль — оставьте эти поля пустыми!
        </div>

        <div class="form-field">
          <%= f.label :password, class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password_confirmation, class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action buffer-top">
          <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<%# Обратите внимание, что она очень похожа на страницу редактирования юзера, %>
<%# что позволяет в подобных случаях использовать один и тот же паршиал form %>
<%# в обоих страницах. %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
        <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
        <%# в поле errors модели (в нашем случае @users). %>
        <% if @user.errors.any? %>
            <div class="form-errors">
              <ul>
                <% for message in @user.errors.full_messages %>
                    <li class="form-error-message"><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%# С помощью методов label и text_field у объекта f мы создаем теги %>
        <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
        <div class="form-field">
          <%= f.label :email, 'Логин (email)', class: 'form-label' %>
          <%= f.text_field :email, class: 'form-text-field' %>
        </div>

        <%# Поступаем аналогично для других полей %>
        <div class="form-field">
          <%= f.label :username, 'Никнейм', class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :name, 'Имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password, 'Пароль', class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action">
          <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
        </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center">
  <h1 class="title-medium">
    <%=	@user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>


  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[foto]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

  <div class="user-details">
    <div class="user-ask-button container text-center">
      <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
    </div>

    <div class="user-statistics container text-center">
      <div class="column-1-3">
        <h1 class="title-small"><%= @questions_count %></h1>
        <p>вопросов</p>
      </div>
      <div class="column-1-3">
        <h1 class="title-small"><%= @answers_count %></h1>
        <p>ответов</p>
      </div>
      <div class="column-1-3">
        <h1 class="title-small"><%= @unanswered_count %></h1>
        <p>безответных</p>
      </div>
    </div>
  </div>

  <div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
    <div class="user-question-form buffer-both">
      <div class="form">
        <%= form_for @new_question do |f| %>
          <%= f.hidden_field :user_id %>

          <div class="form-field">
            <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
            <%= f.text_area :text, class: 'form-textarea' %>
          </div>

          <div class="form-action">
            <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |q| %>
          <%= render partial: 'questions/question', object: q %>
      <% end %>
    </div>
  </div>
</div>